# dubplate version: {{DUBPLATE_VERSION}}

workspace:

  base: /go/src
  path: {{REPOSITORY}}


pipeline:

  run-unit-tests:
    image: golang:{{GO_VERSION}}
    commands:
      - go test -v -race ./...

  # drone mounts the root directory of the repository to the container and sets
  # it as the working directory
  run-linters:
    image: golangci/golangci-lint:v1.32.2-alpine
    commands:
      - golangci-lint run -v

  build-binaries:
    image: golang:{{GO_VERSION}}
    commands:
      - make binaries

  # images are not yet supported
  # build-images:
    # image: HMMMMMMMMM
    # environment:
      # - DOCKER_USERNAME=
