# dubplate version: {{DUBPLATE_VERSION}}

workspace:

  base: /go/src
  path: {{REPOSITORY}}


pipeline:

  run-unit-tests:
    image: golang:1.13.6
    commands:
      - go test -v -race ./...

  # drone mounts the root directory of the repository to the container and sets
  # it as the working directory
  run-linters:
    image: glynhanmer/go-linters:1.13.6-alpine3.11-v0.2.1
    environment:
      - CONCURRENCY=2

  build-binaries:
    image: golang:1.13.6
    commands:
      - make binaries
    # set DOCKER_USERNAME if using docker.Makefile
    # environment:
      # - DOCKER_USERNAME=
